apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  serviceName: rabbitmq
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.10.5-management-alpine
          ports:
            - containerPort: 4369
            - containerPort: 5672
            - containerPort: 15672
            - containerPort: 25672
            - containerPort: 35197
            - name: metrics
              containerPort: 15692
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "400m"
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
        labels:
          app: rabbitmq
      spec:
        storageClassName: storage-rabbitmq
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-rabbitmq
provisioner: k8s.io/minikube-hostpat
reclaimPolicy: Retain
volumeBindingMode: Immediate